<a href="https://colab.research.google.com/github/shivansh2310/Nerd-Stuff/blob/main/Chi_Squared_fit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##chi-square test from scratch

In [5]:
# chisq_area.py
# chi-square test from scratch

import numpy as np
from scipy.stats import chisquare  # for verification

def my_chisq_pval(x, df):
  # x = computed chi-square stat
  # df = degreess of freedom
  # ACM algorithm 299 (calls ACM 209)
  if x < 0.0 or df < 1:
    print("FATAL argument error ")

  a = 0.0  # 299 variable names
  y = 0.0
  s = 0.0
  z = 0.0
  ee = 0.0  # change from e
  c = 0.0

  even = True
  a = 0.5 * x
  if df % 2 == 0: even = True
  else: even = False

  if df > 1: y = my_exp(-a)  # ACM update remark (4)
  if (even == True): s = y
  else: s = 2.0 * gauss(-np.sqrt(x))
  
  if df > 2:
    x = 0.5 * (df - 1.0)
    if even == True: z = 1.0
    else: z = 0.5
    if a > 40.0:  # ACM remark (5)
      if even == True: ee = 0.0
      else: ee = 0.5723649429247000870717135
      c = np.log(a)   # log base e
      while z < x:
        ee = np.log(z) + ee
        s = s + my_exp(c * z - a - ee)  # ACM update remark (6)
        z = z + 1.0
      return s
    else:  # a "lte" 40.0
      if even == True: 
        ee = 1.0
      else:
        ee = 0.5641895835477562869480795 / np.sqrt(a)
          
      c = 0.0
      while z < x:
        ee = ee * (a / z)  # ACM update remark (7)
        c = c + ee
        z = z + 1.0
      return c * y + s
  else:  # df "lte" 2
    return s

def my_exp(x):
  if x < -40.0:  # ACM update remark (8)
    return 0.0
  else:
    return np.exp(x)

def gauss(z):
  # input: z-value (-inf to +inf)
  # output = p under Normal curve from -inf to z
  # ACM 209  

  y = 0.0
  p = 0.0
  w = 0.0

  if z == 0.0:
    p = 0.0
  else:
    y = np.abs(z) / 2
    if y > 3.0:
      p = 1.0
    elif y < 1.0:
      w = y * y
      p = ((((((((0.000124818987 * w \
        - 0.001075204047) * w + 0.005198775019) * w \
        - 0.019198292004) * w + 0.059054035642) * w \
        - 0.151968751364) * w + 0.319152932694) * w \
        - 0.531923007300) * w + 0.797884560593) * y \
        * 2.0
    else:
      y = y - 2.0
      p = (((((((((((((-0.000045255659 * y \
        + 0.000152529290) * y - 0.000019538132) * y \
        - 0.000676904986) * y + 0.001390604284) * y \
        - 0.000794620820) * y - 0.002034254874) * y \
       + 0.006549791214) * y - 0.010557625006) * y \
       + 0.011630447319) * y - 0.009279453341) * y \
       + 0.005353579108) * y - 0.002141268741) * y \
       + 0.000535310849) * y + 0.999936657524

  if z > 0.0:
    return (p + 1.0) / 2
  else:
    return (1.0 - p) / 2 

def my_chisquare(obs, expect):
  x = 0.0
  for i in range(len(obs)):
    x += (obs[i] - expect[i])**2 / expect[i]
  df = len(obs) - 1
  p_val = my_chisq_pval(x, df)
  return (x, p_val)

def main():
  print("\nBegin chi-square demo ")

  obs = [192, 163, 25]
  expect = [180, 180, 20]
  print("\nObserved counts, expected counts: ")
  print(obs)
  print(expect)

  # scipy
  (chi_stat, pvalue) = chisquare(obs, expect)
  print("\nchi_stat, p_val from scipy: ")
  print("%0.8f" % chi_stat)
  print("%0.8f" % pvalue)

  # scratch
  (chi_stat, pvalue) = my_chisquare(obs, expect)
  print("\nchi_stat, p_val from scratch: ")
  print("%0.8f" % chi_stat)
  print("%0.8f" % pvalue)

  if pvalue > 0.05:
    print("\nData suggests obs does not match expect! ")
  else:
    print("\nNo evidence obs and expect do not match ")

  print("\nEnd demo ")

if __name__ == "__main__":
  main()


Begin chi-square demo 

Observed counts, expected counts: 
[192, 163, 25]
[180, 180, 20]

chi_stat, p_val from scipy: 
3.65555556
0.16077044

chi_stat, p_val from scratch: 
3.65555556
0.16077044

Data suggests obs does not match expect! 

End demo 


##Running Chi-Square Tests with Die Roll Data in Python

In [6]:
import numpy as np
a1 = [6, 4, 5, 10]
a2 = [8, 5, 3, 3]
a3 = [5, 4, 8, 4]
a4 = [4, 11, 7, 13]
a5 = [5, 8, 7, 6]
a6 = [7, 3, 5, 9]
dice = np.array([a1, a2, a3, a4, a5, a6])

In [7]:
from scipy import stats

stats.chi2_contingency(dice)

(16.490612061288754,
 0.35021521809742745,
 15,
 array([[ 5.83333333,  5.83333333,  5.83333333,  7.5       ],
        [ 4.43333333,  4.43333333,  4.43333333,  5.7       ],
        [ 4.9       ,  4.9       ,  4.9       ,  6.3       ],
        [ 8.16666667,  8.16666667,  8.16666667, 10.5       ],
        [ 6.06666667,  6.06666667,  6.06666667,  7.8       ],
        [ 5.6       ,  5.6       ,  5.6       ,  7.2       ]]))

In [9]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(dice)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
16.490612061288754


===Degrees of Freedom===
15


===P-Value===
0.35021521809742745


===Contingency Table===
[[ 5.83333333  5.83333333  5.83333333  7.5       ]
 [ 4.43333333  4.43333333  4.43333333  5.7       ]
 [ 4.9         4.9         4.9         6.3       ]
 [ 8.16666667  8.16666667  8.16666667 10.5       ]
 [ 6.06666667  6.06666667  6.06666667  7.8       ]
 [ 5.6         5.6         5.6         7.2       ]]


In [10]:
r1 = np.random.randint(1,7,1000)
r2 = np.random.randint(1,7,1000)
r3 = np.random.randint(1,7,1000)
r4 = np.random.randint(1,7,1000)
r5 = np.random.randint(1,7,1000)

In [11]:
unique, counts1 = np.unique(r1, return_counts=True)
unique, counts2 = np.unique(r2, return_counts=True)
unique, counts3 = np.unique(r3, return_counts=True)
unique, counts4 = np.unique(r4, return_counts=True)
unique, counts5 = np.unique(r5, return_counts=True)

In [12]:
dice = np.array([counts1, counts2, counts3, counts4, counts5])

In [14]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(dice)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
16.872401634228922


===Degrees of Freedom===
20


===P-Value===
0.6612429407863081


===Contingency Table===
[[168.6 167.2 170.2 164.6 165.8 163.6]
 [168.6 167.2 170.2 164.6 165.8 163.6]
 [168.6 167.2 170.2 164.6 165.8 163.6]
 [168.6 167.2 170.2 164.6 165.8 163.6]
 [168.6 167.2 170.2 164.6 165.8 163.6]]


In [17]:
r1 = np.random.randint(1,7,10000)
r2 = np.random.randint(1,7,10000)
r3 = np.random.randint(1,7,10000)
r4 = np.random.randint(1,7,10000)
r5 = np.random.randint(1,7,10000)

In [18]:
unique, counts1 = np.unique(r1, return_counts=True)
unique, counts2 = np.unique(r2, return_counts=True)
unique, counts3 = np.unique(r3, return_counts=True)
unique, counts4 = np.unique(r4, return_counts=True)
unique, counts5 = np.unique(r5, return_counts=True)

In [19]:
dice = np.array([counts1, counts2, counts3, counts4, counts5])

In [20]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(dice)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
14.963290781098925


===Degrees of Freedom===
20


===P-Value===
0.7785042540568157


===Contingency Table===
[[1666.6 1698.  1686.4 1641.8 1663.8 1643.4]
 [1666.6 1698.  1686.4 1641.8 1663.8 1643.4]
 [1666.6 1698.  1686.4 1641.8 1663.8 1643.4]
 [1666.6 1698.  1686.4 1641.8 1663.8 1643.4]
 [1666.6 1698.  1686.4 1641.8 1663.8 1643.4]]


In [15]:
my_rolls_expected = [46.5, 46.5, 46.5, 46.5, 46.5, 46.5]
my_rolls_actual =  [59, 63, 37, 38, 32, 50]
stats.chisquare(my_rolls_actual, my_rolls_expected)

Power_divergenceResult(statistic=17.49462365591398, pvalue=0.003651257113910144)

In [16]:
opp_rolls_expected = [50.5,50.5,50.5,50.5,50.5,50.5]
opp_rolls_actual =  [39,39,46,54,53,72]
stats.chisquare(opp_rolls_actual, opp_rolls_expected)

Power_divergenceResult(statistic=15.158415841584159, pvalue=0.009706469571756566)